# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55f56ab8005aa3c142eba37457be89173789a7ce9c1a59d0cfc7356fa07cd1d5cf1e5e4421e55a1d0aab1b39f488fc6cb180d1215ad0afd78c2bb608805b63ac

test:
  secret_key_base: 40f9eaa4e63b74ae73747acb3b947a20c863c42f762730fc47837414b0c5b03ccf7481e5621fe3b831dcbc02fda9ad7451f2a270bd8c03b3545dd7a52862ebac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
